services:
  projects_catalog_dev:
    build:
      context: .
    container_name: projects_catalog_dev
    volumes:
      - './../:/var/www'
      - './.ssh/:/root/.ssh'
      - './var/database_backups/:/var/www/html/var/database_backups/'
      - '/var/www/docker'
    ports:
    #   - '1536:80'
    #   - '9912:9912'
      - '8002:8002'
    # network_mode: host
    working_dir: /var/www
    depends_on:
      - projects_catalog_dev_db
  projects_catalog_dev_db:
    image: 'mysql:latest'
    container_name: projects_catalog_dev_db
    environment:
      - MYSQL_ROOT_PASSWORD=projectscatalogstrongpassword
      - HOST_IP=host.docker.internal
    ports:
      - '3436:3306'
    volumes:
      - my-datavolume:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  my-datavolume:
