services:
  projects_catalog_dev:
    build:
      context: .
    container_name: projects_catalog_dev
    volumes:
      - './www:/var/www'
      - './.ssh/:/root/.ssh'
    ports:
      - '1536:80'
    working_dir: /var/www
  projects_catalog_dev_db:
    image: 'mysql:latest'
    container_name: projects_catalog_dev_db
    environment:
      - MYSQL_ROOT_PASSWORD=projectscatalogstrongpassword
    ports:
      - '3436:3306'
